project:
  title: "Great Powers in my Backyard: Frontline Ally Support for the U.S. Military"
  type: website
  output-dir: docs

  render:
    - "**/*.qmd"

    # But not this
    - "!Code/"

  resources:
    - "*Appendix/"
    - "*Figures/"

execute:
  freeze: auto

bibliography: References/references.bib
csl: References/apsa.csl

website:
  repo-url: "https://github.com/meflynn/Poland-Surveys"

  page-navigation: true

  navbar:
    pinned: true
    search: true
    right:
      - text: "Appendix"
        href: Appendix/poland_appendix.qmd

format:
  html:
    theme: default
    toc: true
